### ISSUE TITLE
Find dialog needs to move cursor to the end of previous search text

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexgui#12]
A flexgui feature request...

Currently... When the Find text dialog appears, after a previous attempt to find some other text, the cursor is placed in front of the previous text. The user then has to move the cursor to the far end of that text in order to delete it and type in new search text. This forces the user to use a mouse, trackpad or touch of the screen to place the cursor to the end of the field.

It would be better to have the cursor placed at the end of any previous search text to allow the user to quickly delete and replace that text! There would be no need to remove the user’s hand from the keyboard to move the cursor. Saves a step in the “find” process!

**Comment by totalspectrum** [comment]
Thanks, this is an excellent idea. I've updated src/gui.tcl to implement this.
