### ISSUE TITLE
Cannot build fresh git checkout of flexgui (gc_:65: error: Unknown symbol _clkfreq_var & _clkmode_var)

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexgui#15]
On macOS, after a fresh git clone (with --recursive) of flexgui, make install gets 2 errors trying to build sdboot.binary:
 _gc_:65: error: Unknown symbol _clkfreq_var
_gc_:66: error: Unknown symbol _clkmode_var
make[1]: *** [sdboot.binary] Error 1

Build log:
[flexguiBuildError.txt](https://github.com/totalspectrum/flexgui/files/4494086/flexguiBuildError.txt)

**Comment by totalspectrum** [comment]
Thanks for the bug report. It should be fixed now.
