### ISSUE TITLE
Configure commands Flash Command for P1 not saving between sessions.

### ISSUE THREAD

**Issue by reltham** [totalspectrum/flexgui#16]
Using latest from github as of 4pm Sunday 4/19/2020.

If you configure the commands for P1, you will see all 3 commands change. With the run and flash commands using proploader.
Now, if you exit flexgui completely and run again and go look at the configured commands the flash command one has reverted back to the loadp2 line.  The other two commands are still the P1 versions.

**Comment by totalspectrum** [comment]
Thanks, Roy! That should be fixed now.
