### ISSUE TITLE
Update readme to indicate loadp2.mac and fastspin.mac are included

### ISSUE THREAD

**Issue by bartgrantham** [totalspectrum/flexgui#18]
I am jumping into P2 for the first time and I was following directions for installing various tools, including this one.  This note:

> You'll also need to get binary versions of fastspin and loadp2 for your platform, and copy them into the bin folder.

sent me on a 30 minute wild goose chase trying to compile p2gcc, which didn't build (needed `propeller-elf-gcc`), which then sent me looking for that, which was another dead-end.  I finally gave up and compiled just loadp2, only to discover on putting it in flexgui's bin directory that there was already a _newer_ version in the release.

**Comment by totalspectrum** [comment]
Thank you for reporting this, and for actually reading the instructions; I guess many people don't :). Sorry for the confusion, and I've updated the README.md.
