### ISSUE TITLE
Can't cross-compile for Windows from CI server

### ISSUE THREAD

**Issue by DavidZemon** [totalspectrum/flexgui#6]
The Makefile's `TCLROOT` line is hardcoded and is causing the CI server to fail. The Docker image being used by the CI server already has Tcl/Tk installed via `apt`, so `TCLROOT` shouldn't need to be set at all. Can you conditionally set `TCLROOT` based on whether a default installation can be found?

https://ci.zemon.name/viewLog.html?buildId=3697&buildTypeId=Spin2GUI_Windows&tab=buildLog&_focus=93#_state=66

**Comment by totalspectrum** [comment]
Does your Docker contain tcl/tk libraries for Windows? If so, shouldn't it be sufficient to invoke as
   make TCLROOT=/usr/lib/tcltk
or whatever is appropriate?

**Comment by totalspectrum** [comment]
Closing as inactive for a long time. My guess is that the root problem is that the Tcl/Tk libraries for Windows were not present.
