### ISSUE TITLE
flexgui does not seem to create ".flexgui.config" file on macOS

### ISSUE THREAD

**Issue by dgately** [totalspectrum/flexgui#9]
After exec'ing "wish flexgui.tcl" in a Terminal window on macOS (Catalina v10.15.2 in the case), and making changes within the Commands/Configure Commands dialog, I expect the .flexguji.config file to be created either within the flexgui root directory or the user's root directory.

RESULT: no .flexgui.config file is found, anywhere (searched for with $ find . -name ".flexgui.config"). Each new execution of flexgui starts with the default Configure Commands values.

**Comment by totalspectrum** [comment]
Is the flexgui root directory writable by the user running the program? I have it installed in $HOME/flexgui and the file creation seems to work for me.

**Comment by totalspectrum** [comment]
I haven't been able to reproduce this. Please re-open if it happens with flexgui 4.1.x.
